top_usdt_pairs = [{'symbol': 'BTC', 'id': 'bitcoin'}, {'symbol': 'USDC', 'id': 'usd-coin'}, {'symbol': 'ETH', 'id': 'ethereum'}, {'symbol': 'SOL', 'id': 'solana'}, {'symbol': 'NEIRO', 'id': 'neiro-3'}, {'symbol': 'WIF', 'id': 'dogwifcoin'}, {'symbol': 'XRP', 'id': 'ripple'}, {'symbol': 'BNB', 'id': 'binancecoin'}, {'symbol': 'BOME', 'id': 'book-of-meme'}, {'symbol': 'BONK', 'id': 'bonk'}, {'symbol': 'SHIB', 'id': 'shiba-inu'}, {'symbol': 'ENA', 'id': 'ethena'}, {'symbol': 'APT', 'id': 'aptos'}, {'symbol': 'TAO', 'id': 'bittensor'}, {'symbol': 'NEAR', 'id': 'near'}, {'symbol': 'RUNE', 'id': 'thorchain'}, {'symbol': 'FTM', 'id': 'fantom'}, {'symbol': 'PEOPLE', 'id': 'constitutiondao'}, {'symbol': 'SEI', 'id': 'sei-network'}, {'symbol': 'SAGA', 'id': 'saga-2'}, {'symbol': 'ARB', 'id': 'arbitrum'}, {'symbol': 'TIA', 'id': 'celestia'}, {'symbol': 'TRX', 'id': 'tron'}, {'symbol': 'BCH', 'id': 'bitcoin-cash'}, {'symbol': 'NOT', 'id': 'notcoin'}, {'symbol': 'ETHFI', 'id': 'ether-fi'}, {'symbol': 'JUP', 'id': 'jupiter-exchange-solana'}, {'symbol': 'STX', 'id': 'blockstack'}, {'symbol': 'CTXC', 'id': 'cortex'}, {'symbol': 'UNI', 'id': 'uniswap'}, {'symbol': 'ICP', 'id': 'internet-computer'}, {'symbol': 'CHZ', 'id': 'chiliz'}, {'symbol': 'WBTC', 'id': 'wrapped-bitcoin'}, {'symbol': 'STRK', 'id': 'starknet'}, {'symbol': 'IO', 'id': 'io'}, {'symbol': 'FIL', 'id': 'filecoin'}, {'symbol': 'DOT', 'id': 'polkadot'}, {'symbol': 'POL', 'id': 'polygon-ecosystem-token'}, {'symbol': 'GALA', 'id': 'gala'}, {'symbol': 'ALT', 'id': 'altlayer'}, {'symbol': 'JTO', 'id': 'jito-governance-token'}, {'symbol': 'AXL', 'id': 'axelar'}, {'symbol': 'XAI', 'id': 'xai-blockchain'}, {'symbol': 'HBAR', 'id': 'hedera-hashgraph'}, {'symbol': 'HMSTR', 'id': 'hamster-kombat'}, {'symbol': 'DYDX', 'id': 'dydx-chain'}, {'symbol': 'CATI', 'id': 'catizen'}, {'symbol': 'ZK', 'id': 'zksync'}, {'symbol': 'METIS', 'id': 'metis-token'}, {'symbol': 'IQ', 'id': 'everipedia'}]
s = ''
for i in top_usdt_pairs:
    s += i['symbol'] + ','

print(s[:-1])


"""
BTC,USDC,ETH,SOL,NEIRO,WIF,XRP,BNB,BOME,BONK,SHIB,ENA,APT,TAO,NEAR,RUNE,FTM,PEOPLE,SEI,SAGA,ARB,TIA,TRX,BCH,NOT,ETHFI,
JUP,STX,CTXC,UNI,ICP,CHZ,WBTC,STRK,IO,FIL,DOT,POL,GALA,ALT,JTO,AXL,XAI,HBAR,HMSTR,DYDX,CATI,ZK,METIS,IQ
"""